name: Auto EUserv

on:
  schedule:
    - cron: "0 1 4 * *" # 每月 4 号 北京时间 09:00 运行
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9" # 指定Python3.x

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run script
        env:
          EUSERV_USERNAME: ${{ secrets.EUSERV_USERNAME }}
          EUSERV_PASSWORD: ${{ secrets.EUSERV_PASSWORD }}
          TRUECAPTCHA_USERID: ${{ secrets.TRUECAPTCHA_USERID }}
          TRUECAPTCHA_APIKEY: ${{ secrets.TRUECAPTCHA_APIKEY }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          IMAP_SERVER: ${{ secrets.IMAP_SERVER }}
          MAIL_ADDRESS: ${{ secrets.MAIL_ADDRESS }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
        run: python Github_Action.py
