name: Auto EUserv

on:
  schedule:
    - cron: "27 4 18 * *" # 每月18号 北京时间 12:27
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run script
        id: run_script
        continue-on-error: true 
        env:
          EUSERV_USERNAME: ${{ secrets.EUSERV_USERNAME }}
          EUSERV_PASSWORD: ${{ secrets.EUSERV_PASSWORD }}
          TRUECAPTCHA_USERID: ${{ secrets.TRUECAPTCHA_USERID }}
          TRUECAPTCHA_APIKEY: ${{ secrets.TRUECAPTCHA_APIKEY }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          IMAP_SERVER: ${{ secrets.IMAP_SERVER }}
          MAIL_ADDRESS: ${{ secrets.MAIL_ADDRESS }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
        run: python Github_Action.py

      - name: Upload Debug Pages
        if: always() 
        uses: actions/upload-artifact@v4
        with:
          name: login-debug-files
          path: "*.html" 
          retention-days: 1
          if-no-files-found: ignore # 核心修改：如果没有html文件，直接忽略不报警

      - name: Final Status
        if: steps.run_script.outcome == 'failure'
        run: exit 1
